build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64

    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3

    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - python --version
  - python -c "import sys,platform,struct;print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment
  python=%PYTHON_VERSION% numpy pandas scipy matplotlib pytest"
  - activate test-environment
  - conda install libpython numpy matplotlib numba scipy cython pytest pytest-cov
  - echo [build] > %CONDA_PREFIX%\Lib\distutils\distutils.cfg
  - python setup.py install

test_script:
  - pytest .

after_test:
  # 如果测试成功，为项目创建二进制包。
  - python setup.py bdist_wheel"
  - python setup.py bdist_wininst"
  - ps: "ls dist"

artifacts:
  # 在 ci.appveyor.com 构建报告中存档生成的包。
  - path: dist\*
